### ISSUE TITLE
Scholars' descriptions are recognized as programs instead of transcripts

### ISSUE THREAD

**Issue by avatousiou** [afred/openvault#843] opened 2014-10-07 20:04 UTC
http://openvault.wgbh.org/catalog/openvault:55046 is being recognized as a program but it should be a transcript for this video: http://openvault.wgbh.org/catalog/e83af1-joyce-chen-cooks-egg-foo-yung.

This is also causing an issue where the program link on the video page links to this transcript instead of the proper program here: http://openvault.wgbh.org/catalog/openvault:31490

**Comment by Muraszko** [comment] 2015-03-04 12:42
Looks like this issue got fixed with the re-ingest!
I can confirm the extended description log files are behaving like transcripts on each Joyce Chen video page, which is what we wanted.
Closing.

**Closed by Muraszko** 2015-03-04 12:42 UTC
