### ISSUE TITLE
Ingest Set of Updated Open Vault XML

### ISSUE THREAD

**Issue by Muraszko** [afred/openvault#1219] opened 2015-04-01 14:50 UTC
Please find three PBCore xml files here and ingest them into Open Vault:
smb://deptfs.wgbh.org/dept/MLA/OpenVault_Upload/04012015_upload_test

These two are for a single video clip (video xml and thumbnail xml) with relationships expressed
```
sbro-mla000927-thumb.xml
sbro-mla000927-video.xml
```
This one is for a single text only clip description
```
sbro-sbro036.xml
```

**DONE WHEN**
The files have been ingested into Open Vault and are checked to be working correctly on the website by @muraszko

**Comment by mccalluc** [comment] 2015-04-08 17:21
2 of 3 worked.
```
$ RAILS_ENV=production bundle exec rake openvault:ingest file=/home/openvault/04012015_upload_test/sbro-sbro036.xml
...
Nokogiri::XML::SyntaxError: StartTag: invalid element name
/wgbh/http/openvault/shared/bundle/ruby/2.0.0/gems/nokogiri-1.6.5/lib/nokogiri/xml/document.rb:55:in `read_memory'
/wgbh/http/openvault/shared/bundle/ruby/2.0.0/gems/nokogiri-1.6.5/lib/nokogiri/xml/document.rb:55:in `parse'
/wgbh/http/openvault/releases/20150408133835/lib/openvault.rb:19:in `XML'
/wgbh/http/openvault/releases/20150408133835/lib/openvault/pbcore/ingester.rb:106:in `ng_xml'
```

I'm going to try ingesting this locally to reproduce...

**Comment by mccalluc** [comment] 2015-04-08 17:29
```
$ tidy -xml /Volumes/dept/MLA/OpenVault_Upload/04012015_upload_test/sbro-sbro036.xml
line 86 column 3 - Error: unexpected </pbcoreDescriptionDocument> in <pbcoreSubject>
```
```xml
  <pbcoreSubject subjectType="Personalities">Abdalah<</pbcoreSubject>
  <pbcoreSubject subjectType="Personalities">Childress, Alice<</pbcoreSubject>
```
Fixed the copies on the department server; will scp and reingest. (@Muraszko : is there anything more systematic which needs to be addressed?)

**Comment by mccalluc** [comment] 2015-04-08 17:35
Last ingest worked. Have not actually tried to look at any of the records. (Do we worry about slugs?) Passing back to @Muraszko, per the done criterion.

**Comment by afred** [comment] 2015-04-08 17:36
@mccalluc after scp'ing, could you add it to the stash repo? If you can't do that b/c of user credintials still lacking.. let me know and i will. thanks

**Comment by Muraszko** [comment] 2015-04-08 18:35
@mccalluc Searching with the uuidgen value I only see [one of the] three(http://openvault.wgbh.org/catalog/openvault:43650) records displaying.

07F1FF02-00C2-4932-AE3A-9695996504ED
and
B1EDF27F-D1C5-47D8-8BEB-809D8AE9D78C

Are they not being indexed?  Is the website not set up to display
```
<pbcoreAssetType>Clip</pbcoreAssetType>
```
Types of records?

**Comment by mccalluc** [comment] 2015-04-08 18:48
Trying it locally, it looks like it fails silently: No error message, but the data doesn't make it in there, either. Investigating.

**Comment by mccalluc** [comment] 2015-04-08 19:23
B1EDF27F-D1C5-47D8-8BEB-809D8AE9D78C is up: http://openvault.wgbh.org/catalog/openvault:43651

Looking at the other one.

**Comment by mccalluc** [comment] 2015-04-08 19:34
07F1FF02-00C2-4932-AE3A-9695996504ED is up, with a similar tweak: http://openvault.wgbh.org/catalog/openvault:43652

(Classified as video? But there is no video to play...)

**Comment by mccalluc** [comment] 2015-04-08 19:39
Metadata committed with https://atlas.wgbh.org/stash/projects/MLA/repos/openvault_ingest_data/commits/9aa8b28638f8cf0367b46994736f96d7b5080658

**Closed** 2015-04-27 12:44 UTC
